<?php

namespace App\Controller\Admin;

use App\Entity\Hostel;
use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Security\Core\User\UserInterface;

class HostelCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Hostel::class;
    }

    public function configureFields(string $pageName): iterable
    {

        // id fields
        $id = IdField::new('id');
        $user_id = IdField::new('user_id');

        // data fields
        $hostel_name = TextField::new('hostel_name', 'Name');
        $address = TextField::new('address', 'Straße');
        $address_sub = TextField::new('address_sub', 'Adress zusatz');
        $postcode = TextField::new('postcode', 'PLZ');
        $city = TextField::new('city', 'Stadt');
        $state = TextField::new('state', 'Bundesland'); // todo add dropdown
        $country = TextField::new('country', 'Land');// todo add dropdown
        $country_id = TextField::new('country_id'); // intern filed only
        $longitude = NumberField::new('longitude');
        $latitude = NumberField::new('latitude');
        $phone = NumberField::new('phone', 'Festnezt');
        $mobile = NumberField::new('mobile');
        $fax = TextField::new('fax');

        // on or offline
        $status = BooleanField::new('status');


        // output fields by page
        if (Crud::PAGE_INDEX === $pageName) {
            return [$user_id, $hostel_name, $address, $postcode, $city, $status];
        } elseif (Crud::PAGE_DETAIL === $pageName) {
            return [
                $id,
                $user_id,
                $hostel_name,
                $address,
                $address_sub,
                $postcode,
                $city,
                $state,
                $country,
                $country_id,
                $longitude,
                $latitude,
                $phone,
                $mobile,
                $fax,
            ];
        } elseif (Crud::PAGE_NEW === $pageName) {
            return [$hostel_name, $address, $postcode];
        } elseif (Crud::PAGE_EDIT === $pageName) {
            return [$id, $user_id, $hostel_name, $address, $postcode];
        }
    }


    /**
     * Create a new hostel with
     * the id from the logged in user
     * a user cant have many hostel's
     *
     * @param string $entityFqcn
     * @return Hostel|mixed
     */
    public function createEntity(string $entityFqcn)
    {
        $user = $this->get('security.token_storage')->getToken()->getUser();

        $hostel = new Hostel();
        $hostel->setUserId((int)$user->getId());

        return $hostel;
    }


    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions($actions); // TODO: Change the autogenerated stub
    }


}
