<?php

namespace App\Controller\Admin;

use App\Entity\HostelGallery;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use FM\ElfinderBundle\Form\Type\ElFinderType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Security\Core\Security;

class HostelGalleryCrudController extends AbstractCrudController
{
    private $hostels;

    public function __construct(Security $security)
    {
        if (null !== $security->getUser()) {
            $this->user = $security->getUser();
            $this->hostels = $this->user->getHostels();
        }

        //print_r($user->getHostels()[0]->getId());
    }

    public static function getEntityFqcn(): string
    {
        return HostelGallery::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->addFormTheme('@FMElfinderBundle/Form/elfinder_widget.html.twig');
    }


    public function configureFields(string $pageName): iterable
    {

        $id = IdField::new('id');
        $hostel_id = IntegerField::new('hostel_id', 'Bild zu Unterkunft')
            ->setFormType(ChoiceType::class)
            ->setFormTypeOptions(
                [

                    'choices' => [
                        $this->buildHostelChoices(),
                    ],

                    'group_by' => 'id',

                ]
            );
        $name = TextField::new('name', 'Text für Suchmaschiene');
        $image = ImageField::new('image', 'Bild')
            ->setFormType(ElFinderType::class)
            ->setFormTypeOptions(['instance' => 'hostel', 'enable' => true])
            ->setHelp('Vorzugsweise 1000x600 Pixel in guter Qualität');
        $status = BooleanField::new('status');

        switch ($pageName) {
            case Crud::PAGE_INDEX:
            case Crud::PAGE_DETAIL:
                return [
                    $id,
                    $name,
                    $image,
                    $status,
                ];
                break;
            case Crud::PAGE_NEW:
            case Crud::PAGE_EDIT:
                return [
                    $hostel_id,
                    $name,
                    $image,
                    $status,
                ];
                break;
        }

    }

    public function createEntity(string $entityFqcn)
    {
        $gallery = new HostelGallery();
        $gallery->setStatus(true);

        return $gallery; // TODO: Change the autogenerated stub
    }

    #############################
    #
    # Helper function protected
    #
    #############################

    protected function buildHostelChoices()
    {
        foreach ($this->hostels as $hostel) {
            $hostel_names[$hostel->getHostelName()] = $hostel->getId();
        }

        return $hostel_names;
    }
}
