<?php

namespace App\Controller\Admin;

use App\Entity\HostelGallery;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IntegerField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use FM\ElfinderBundle\Form\Type\ElFinderType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Security\Core\Security;

class HostelGalleryCrudController extends AbstractCrudController
{
    public function __construct(Security $security)
    {
        if (null !== $security->getUser()) {
            $this->user = $security->getUser();
            $this->hostels = $this->user->getHostels();
        }

        //print_r($user->getHostels()[0]->getId());
    }

    public static function getEntityFqcn(): string
    {
        return HostelGallery::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->addFormTheme('@FMElfinderBundle/Form/elfinder_widget.html.twig');
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            /*IdField::new('id'),*/
            IntegerField::new('hostel_id'),
            TextField::new('name'),
            ImageField::new('image', 'Bild')
                ->setFormType(ElFinderType::class)
                ->setFormTypeOptions(['instance' => 'hostel', 'enable' => true])
                ->setHelp('Vorzugsweise 1000x600 Pixel in guter Qualität'),
            BooleanField::new('status'),

        ];
    }

    public function createEntity(string $entityFqcn)
    {
        return parent::createEntity($entityFqcn); // TODO: Change the autogenerated stub
    }
}
