<?php


namespace App\Controller\Admin;


use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Config\UserMenu;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class UserProfilDashboardController extends AbstractDashboardController
{

    /**
     * @Route("/admin/user/profil", name="admin_user_profil")
     */
    public function index(): Response
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function configureDashboard(): Dashboard
    {
        return parent::configureDashboard(); // TODO: Change the autogenerated stub
    }

    public function configureAssets(): Assets
    {
        return parent::configureAssets(); // TODO: Change the autogenerated stub
    }

    public function configureMenuItems(): iterable
    {
        parent::configureMenuItems(); // TODO: Change the autogenerated stub
    }

    public function configureUserMenu(UserInterface $user): UserMenu
    {
        return parent::configureUserMenu($user); // TODO: Change the autogenerated stub
    }

    public function configureCrud(): Crud
    {
        return parent::configureCrud(); // TODO: Change the autogenerated stub
    }

    public function configureActions(): Actions
    {
        return parent::configureActions(); // TODO: Change the autogenerated stub
    }

    public function configureFilters(): Filters
    {
        return parent::configureFilters(); // TODO: Change the autogenerated stub
    }
}