<?php


namespace App\Controller\Admin;


use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use EasyCorp\Bundle\EasyAdminBundle\Config\UserMenu;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractDashboardController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class UserDashboardController extends AbstractDashboardController
{

    /**
     * @Route("/user", name="user")
     */
    public function index(): Response
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function configureDashboard(): Dashboard
    {
        return parent::configureDashboard(); // TODO: Change the autogenerated stub
    }

    public function configureMenuItems(): iterable
    {
        yield MenuItem::linkToCrud('Mein Konto','fa fa-id-card',UserCrudController::class);
    }

    public function configureUserMenu(UserInterface $user): UserMenu
    {
        return parent::configureUserMenu($user); // TODO: Change the autogenerated stub
    }

    public function configureCrud(): Crud
    {
        return parent::configureCrud(); // TODO: Change the autogenerated stub
    }
}